version : '2'
services:

  frontend:
    build:  ./client
    image: miwtoo/frontend:v1
    ports:
      - 4200:80

  backend:
    build: ./server
    image: miwtoo/server:v1
    ports:
      - 8080:8080
